version: '2'

services:
  webServer1:
    image: apache_confd
    environment:
      - server_number=1
    volumes:
      - apache_data1:/usr/local/apache2/htdocs

  webServer2:
    image: apache_confd
    environment:
      - server_number=2
    volumes:
      - apache_data2:/usr/local/apache2/htdocs

  webServer3:
    image: apache_confd
    environment:
      - server_number=3
    volumes:
      - apache_data3:/usr/local/apache2/htdocs

  proxy:
    build:
      context:  ./NginxContainer
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - nginx_data:/etc/nginx

volumes:
    apache_data1:
    apache_data2:
    apache_data3:
    nginx_data:
